SELECT CUSTOMRECORD_SR_STATE_REGISTRATION.name || '+/app/site/hosting/scriptlet.nl?script=1504&deploy=1&page=stateofregistration&idrec=' || CUSTOMRECORD_SR_STATE_REGISTRATION.id as ID_link
	,CUSTOMRECORD_SR_STATE_REGISTRATION.altname as NAME
	,CUSTOMRECORD_SR_STATE_REGISTRATION.custrecord_sr_statereg_subsidiary as SUBSIDIARY
	,CUSTOMRECORD_SR_STATE_REGISTRATION.custrecord238 as DESCRIPTION
	,CUSTOMRECORD_SR_STATE_REGISTRATION.custrecord239 as STATE
	,CUSTOMRECORD_SR_STATE_REGISTRATION.custrecord_sr_registration_number as REGISTRATION_NO
	,CUSTOMRECORD_SR_STATE_REGISTRATION.custrecord_sr_registration_date as REGISTRATION_DATE
FROM CUSTOMRECORD_SR_STATE_REGISTRATION
WHERE CUSTOMRECORD_SR_STATE_REGISTRATION.id > ?