SELECT CUSTOMRECORD_SR_VISA.name || '+/app/site/hosting/scriptlet.nl?script=1504&deploy=1&page=visa&idrec=' || CUSTOMRECORD_SR_VISA.id as ID_link
	,CUSTOMRECORD_SR_VISA.name || '+/app/site/hosting/scriptlet.nl?script=1504&deploy=1&page=visa&idrec=' || CUSTOMRECORD_SR_VISA.id as ID_link
	,CUSTOMRECORD_SR_VISA.created as DATE_CREATED
	,CUSTOMRECORD_SR_VISA.lastmodified as LAST_MODIFIED
	,CUSTOMRECORD_SR_VISA.custrecord51 as ROCKETEER_PASSPORT_NUMBER
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord53) as ROCKETEER
	,CUSTOMRECORD_SR_VISA.custrecord_sr_visa_country_origin as ROCKETEER_COUNTRY_OF_ORIGIN
	,CUSTOMRECORD_SR_VISA.custrecord_sr_visa_passport_expiry as ROCKETEER_PASSPORT_EXPIRY_DATE
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord47) as VISA_TYPE
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord48) as VISA_ISSUING_COUNTRY
	,CUSTOMRECORD_SR_VISA.custrecord50 as VISA_EXPIRY_DATE
	,CUSTOMRECORD_SR_VISA.custrecord52 as NOTES
	,CUSTOMRECORD_SR_VISA.custrecord_sr_visa_app_stat as VISA_APPLICATION_STATUS
FROM CUSTOMRECORD_SR_VISA
WHERE CUSTOMRECORD_SR_VISA.id > ?