SELECT CUSTOMRECORD_SR_VISA.name as VISA_NUMBER
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord53) as ROCKETEER
	,CUSTOMRECORD_SR_VISA.custrecord_sr_visa_country_origin as ROCKETEER_COUNTRY_OF_ORIGIN
	,CUSTOMRECORD_SR_VISA.custrecord_sr_visa_passport_expiry as ROCKETEER_PASSPORT_EXPIRY_DATE
	,CUSTOMRECORD_SR_VISA.custrecord51 as ROCKETEER_PASSPORT_NUMBER
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord47) as VISA_TYPE
	,BUILTIN.DF(CUSTOMRECORD_SR_VISA.custrecord48) as VISA_ISSUING_COUNTRY
	,CUSTOMRECORD_SR_VISA.custrecord49 as VISA_ISSUE_DATE
	,CUSTOMRECORD_SR_VISA.custrecord50 as VISA_EXPIRY_DATE
FROM CUSTOMRECORD_SR_VISA
WHERE CUSTOMRECORD_SR_VISA.id = ?